import css from './Main.module.css'

export const Main = (props) => {
    return (
        <div className={css.container}>
            <div className={`${css.item} ${css.span_column}`} />
            <div className={`${css.item} ${css.span_row}`} />
            <div className={`${css.item} ${css.span_column} ${css.span_row}`} />
            <div className={css.item_container}>
                <div className={`${css.item} ${css.span_column} ${css.span_row}`} />
                <div className={css.item}  />
                <div className={`${css.item} ${css.span_row}`} />
                <div className={`${css.item} ${css.span_column}`} />
                
            </div>
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
            <div className={css.item} />
        </div>
    );
}